#  Update system
# sudo yum update -y

# # Install development tools
# sudo yum groupinstall -y "Development Tools"

# # Install NVIDIA driver and CUDA repositories
# sudo yum install -y nvidia-driver-latest-dkms
# sudo yum install -y cuda

# # Install NVIDIA Container Toolkit repository
# curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
#     sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo

- name: Execute system setup tasks
  become: true
  ansible.builtin.block:

    - name: Update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true
      register: yum_update
      when: update | default(false) | bool

    - name: Reboot system after kernel updates
      ansible.builtin.reboot:
        reboot_timeout: 600
        msg: "Rebooting to load new kernel headers and kernel devel"
      when:
        - update | default(false) | bool
        - yum_update is changed

    - name: Install Development Tools package group
      ansible.builtin.yum:
        name: '@Development Tools'
        state: present

    - name: Download NVIDIA Container Toolkit repository configuration
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
        dest: /etc/yum.repos.d/nvidia-container-toolkit.repo

    - name: Install NVIDIA Container Toolkit package
      ansible.builtin.yum:
        name: nvidia-container-toolkit
        state: present
        update_cache: true
