- name: Include RedHat specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '9'

- name: Include Amazon Linux 2 specific tasks
  ansible.builtin.include_tasks: amazon2.yml
  when:
    - ansible_distribution == 'Amazon'

- name: Include Ollama setup tasks
  ansible.builtin.include_tasks: ollama.yml
