- include_tasks: redhat.yml
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '9'
- include_tasks: amazon2.yml
  when:
    - ansible_distribution == 'Amazon'
- include_tasks: ollama.yml
