# sudo dnf config-manager --enable rhel-9-appstream-rhui-rpms
# sudo dnf -y install kernel-headers kernel-devel
# sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
# sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
# sudo dnf -y module install nvidia-driver:latest-dkms
# sudo dnf -y install cuda-toolkit

- name: Execute RedHat setup tasks
  become: true
  block:
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
      register: yum_update
      when: update | default(false) | bool

    - name: Reboot system after kernel updates
      ansible.builtin.reboot:
        reboot_timeout: 600
        msg: "Rebooting to load new kernel if installed"
      when:
        - update | default(false) | bool
        - yum_update is changed
        - "'kernel' in yum_update.stdout"

    - name: Add rhel-9-appstream-rhui-rpms
      community.general.dnf_config_manager:
        name: rhel-9-appstream-rhui-rpms
        state: enabled

    - name: Install kernel-headers and kernel-devel
      ansible.builtin.dnf:
        name:
          - kernel-headers
          - kernel-devel
        state: present
        update_cache: true

    - name: Install GPG key for EPEL
      ansible.builtin.rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
        state: present

    - name: Add epel repository
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: Add cuda repository
      ansible.builtin.get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
        dest: /etc/yum.repos.d/cuda-rhel9.repo

    - name: Install nvidia-driver:latest-dkms
      ansible.builtin.dnf:
        name: '@nvidia-driver:latest-dkms'
        state: present
        update_cache: true

    - name: Install cuda-toolkit
      ansible.builtin.dnf:
        name: cuda-toolkit
        state: present

    - name: Install newer Python
      ansible.builtin.dnf:
        name:
          - python3.11
          - python3.11-pip
        state: present
