---
- name: Find instance by name
  amazon.aws.ec2_instance_info:
    endpoint_url: "{{ aws_endpoint_url | default(omit) }}"
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ instance_name }}"
      instance-state-name:
        - running
        - pending
        - stopping
        - stopped
  register: instance_info

- name: Notify if instance not found
  ansible.builtin.debug:
    msg: "No instance found with name: {{ instance_name }}"
  when: instance_info.instances | length == 0

- name: Stop the instance
  amazon.aws.ec2_instance:
    endpoint_url: "{{ aws_endpoint_url | default(omit) }}"
    instance_ids: "{{ instance_info.instances[0].instance_id }}"
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
    state: stopped
    wait: true
  register: stop_result
  when:
    - instance_info.instances | length > 0
    - instance_info.instances[0].state.name != 'stopped'

- name: Show stop result
  ansible.builtin.debug:
    msg: "Instance {{ instance_name }} ({{ instance_info.instances[0].instance_id }}) has been stopped"
  when:
    - instance_info.instances | length > 0
    - stop_result is changed
